"policy_path" : "BUGGY_WP_TEST.zip"
"motors_on" : True 
"controller_source" : "nn" # nn/joystick
"update_rate" : 100
"update_period" : 0.01
"motor_scalar" : 0.3
"throttle_offset" : 0.5
"target_proximity_threshold" : 0.6
"n_data_gathering_steps" : 20000
"wp_sequence" : "three_pole" # "rnd", "two_pole", "three_pole", "four_pole"


