"policy_path" : "BUGGY_WP_TEST.zip"
"motors_on" : True 
"controller_source" : "nn" # "joystick" # nn/joystick
"update_period" : 0.005
"motor_scalar" : 0.4
"throttle_offset" : 0.5
"target_proximity_threshold" : 0.6
"n_data_gathering_steps" : 4000
"wp_sequence" : "three_pole" # "rnd", "two_pole", "three_pole", "four_pole"
"opensimplex_scalars" : [50, 500]


