"policy_eef" : "EEF_TD3_OPTUNA_policy.zip"
"policy_straight" : "OBTACLE_TD3_OPTUNA_policy.zip"
"urdf_name" : "hexapod_normal.urdf"
"motors_on" : True
"time_prints" : False
"target_vel_source" : "joystick" # rnd/joystick/ros
"ahrs_source" : "rs"
"imu_ahrs_update_period" : 0.01
"update_period" : 0.05
"angle_increment" : 0.06
"max_servo_speed" : 400
"max_servo_torque" : 1024
"use_contacts" : True
"velocities_and_torques" : False
"phase_scalar": 0.175
"z_aux_scalar" : 0.0386 # 0.05
"x_mult_scalar" : 0.01992 # 0.05
"joints_rads_low" : [-0.6, -0.853, -0.60]
"joints_rads_high" : [0.6, 0.534, 0.9]
"turn_transition_thresh" : 0.4
"turn_clip_value" : 0.5
