"policy_straight" : "ZTA_SB_policy.zip" #"JMA_SB_policy.zip"
"urdf_name" : "hexapod_normal.urdf"
"motors_on" : True 
"time_prints" : False
"target_vel_source" : "joystick" # rnd/joystick/ros
"ahrs_source" : "rs"
"imu_ahrs_update_period" : 0.01
"update_period" : 0.01
"max_servo_speed" : 500
"max_servo_torque" : 1024
"policy_hid_dim" : 128
"use_contacts" : True
