"policy_direct" : "OBSTACLE_TD3_OPTUNA_policy.zip"
"policy_cw" : "CW_TD3_OPTUNA_policy.zip"
"policy_ccw" : "CCW_TD3_OPTUNA_policy.zip"
"motors_on" : True
"time_prints" : False
"target_vel_source" : "joystick" # rnd/joystick/ros
"ahrs_source" : "rs"
"imu_ahrs_update_period" : 0.01
"update_period" : 0.05
"angle_increment" : 0.08
"max_servo_speed" : 500
"max_servo_torque" : 1023
"use_contacts" : True
"velocities_and_torques" : False
"turn_joints_rads_low" : [-0.5, -1.0, 0.5]
"turn_joints_rads_high" : [0.5, 0.0, 1.5]
"direct_joints_rads_low" : [-0.6, -1.17, 0.16]
"direct_joints_rads_high" : [0.6, 0.36, 1.32]
"turn_transition_thresh" : 0.4
"turn_clip_value" : 0.6
"dynamic_time_feature_ub" : 0.6
"dynamic_max_steps" : 180
"z_pressure_coeff" : 0.1
"turn_coeff" : 0.03
"x_mult" : 0.06
"y_offset" : 0.11
"z_mult" : 0.05
"z_offset" : -0.12
"z_lb" : 1
