"policy_straight" : "ZTA_SB_policy.zip" 
"urdf_name" : "hexapod_normal.urdf"
"motors_on" : True 
"time_prints" : False
"target_vel_source" : "joystick" # rnd/joystick/ros
"ahrs_source" : "rs"
"imu_ahrs_update_period" : 0.01
"update_period" : 0.01
"angle_increment" : 0.026
"max_servo_speed" : 500
"max_servo_torque" : 1024
"use_contacts" : True
"read_true_torques" : False
"phase_scalar" : 0.25
"z_aux_scalar" : 0.05
"phase_offset_scalar" : 1.2
