"policy_path" : "QUADCOPTER_STAB_2METRES.zip"
"motors_on" : False
"controller_source" : "pid" # nn/pid
"target_vel_source" : "joystick" # still/rnd/joystick
"ahrs_source" : "rs"
"target_pos" : [0, 0, 2.0]
"starting_pos" : [0, 0, 2.0]
"update_period" : 0.01
"joystick_mapping" : [1,3,4,0]

