"policy_path" : "QUADCOPTER_STAB_2METRES.zip"
"motors_on" : True
"controller_source" : "pid" # nn/pid
"target_vel_source" : "joystick" # still/rnd/joystick
"ahrs_source" : "imu"
"target_pos" : [0, 0, 2.0]
"starting_pos" : [0, 0, 2.0]
"update_period" : 0.01
"joystick_mapping" : [2,3,0,1]

